// Copyright 2025 Joshua Lucas (joshdlucas@gmail.com)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define PERMISSIVE_HOLD
#define TAPPING_TERM 250

#define PLOOPY_DRAGSCROLL_MOMENTARY
//#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_RATIO -0.667
#define PLOOPY_DRAGSCROLL_OPTIONS { -0.06, -0.04, -0.02}
#define PLOOPY_DRAGSCROLL_MULTIPLIER_V -0.02
#define PLOOPY_DRAGSCROLL_MULTIPLIER_H PLOOPY_DRAGSCROLL_MULTIPLIER_V * PLOOPY_DRAGSCROLL_RATIO
#define PLOOPY_DRAGSCROLL_DEFAULT 1

#define PLOOPY_DPI_OPTIONS { 400, 800, 1200, 1600 }
#define PLOOPY_DPI_DEFAULT 2
#define PLOOPY_DPI_SNIPE 0